import Head from "next/head";
import Header from "@/components/Header";
import Hero from "@/components/Hero";
import About from "@/components/About";
import Experience from "@/components/Experience";
import Skills from "@/components/Skills";
export default function Home() {
  return (
    <div className="bg-[rgb(36,36,36)] text-white h-screen snap-y snap-mandatory overflow-scroll z-0">
      <Head>
        <title>Emmanuel Bwire</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      {/* Hero */}
      <section id="hero" className=" snap-start">
        <Hero />
      </section>

      <section id="about" className="h-screen snap-center py-10">
        <About />
      </section>

      <section id="experience" className="snap-center h-screen">
        <Experience />
      </section>

      {/* Skills */}
      <section id="skills" className="snap-start h-screen">
        <Skills />
      </section>
    </div>
  );
}
