import Head from "next/head";
import Header from "@/components/Header";
import Hero from "@/components/Hero";
import About from "@/components/About";
import Experience from "@/components/Experience";
import Skills from "@/components/Skills";
import Projects from "@/components/Projects";
import Contact from "@/components/Contact";
import Link from "next/link";
import Footer from "@/components/Footer";
export default function Home() {
  return (
    <div className="relative bg-[rgb(36,36,36)] text-white h-screen snap-y snap-mandatory overflow-y-scroll z-0 overflow-x-hidden">
      <Head>
        <title>Emmanuel Bwire</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      {/* Hero */}
      <section id="hero" className=" snap-center">
        <Hero />
      </section>

      <section id="about" className="h-auto snap-center">
        <About />
      </section>

      <section id="experience" className="snap-start h-auto">
        <Experience />
      </section>

      {/* Skills */}
      <section id="skills" className="snap-center h-screen">
        <Skills />
      </section>

      {/* Projects */}
      <section id="projects" className="snap-start h-screen">
        <Projects />
      </section>
      {/* Contacts */}
      <section id="contact" className="snap-end h-screen">
        <Contact />
      </section>
      <Link href="#hero">
        <Footer />
      </Link>
    </div>
  );
}
